team_tasks_manager/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('team_tasks_managers.urls', namespace = 'team_tasks_managers')),
    path(r'^users/', include('users.urls', namespace = 'users'))
]

team_tasks_managers/urls.py
"""Defines URL patterns for team_tasks_managers"""

from django.conf.urls import url
from . import views

app_name = 'team_tasks_managers'
urlpatterns = [
    #home page
    url(r'^$', views.index, name = 'index'),
    #list of all tasks
    url(r'^tasks/$', views.tasks, name = 'tasks'),
    #certain task's page
    url(r'^task/(?P<task_id>\d+)/$', views.task, name = 'task'),
    #website used to add new task
    url(r'^new_task/$', views.new_task, name = 'new_task'),
    #save changes in completed tasks
    url(r'^cross_off/(?P<task_id>\d+)/$', views.cross_off, name = "cross_off"),
    url(r'^uncross/(?P<task_id>\d+)/$', views.uncross, name = "uncross"),
]

users/urls.py
"""Defines URL patterns for users app"""

from django.conf.urls import url
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'
urlpatterns = [
    #login page
    url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name = 'login'),
    #logout page
    url(r'^logout/$', views.logout_view, name = 'logout'),
    #Registration page
    url(r'^register/$', views.register, name = 'register')
]

team_tasks_managers/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    """task to be completed by team member(s)"""
    description = models.CharField(max_length = 200)
    deadline = models.CharField(max_length = 30)
    assigned_to = models.ForeignKey(User, on_delete = models.DO_NOTHING)
    completed = models.BooleanField(default = False)

    def __str__(self):
        return self.description

users/models.py
from django.db import models

# Create your models here.

team_tasks_managers/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['description', 'deadline', 'completed']
        labels = {'description': 'task', 'deadline' : 'deadline', 'completed' : 'completed'}

team_tasks_managers/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from .models import Task
from .forms import TaskForm

# Create your views here.
def index(request):
    """Home page for Team Tasks Managers app"""
    return render(request, 'team_tasks_managers/index.html')

def tasks(request):
    """Displays all tasks"""
    tasks = Task.objects.filter(assigned_to=request.user).order_by('description')
    context = {'tasks': tasks}
    return render(request, 'team_tasks_managers/tasks.html', context)

@login_required
def task(request, task_id):
    """Displays given task"""
    task = Task.objects.get(id = task_id)
    if task.assigned_to != request.user:
        raise Http404
    context = {'task': task}
    return render(request, 'team_tasks_managers/task.html', context)

@login_required
def new_task(request):
    """Add new topic"""
    if request.method != 'POST':
        #No data passed, need to create a new form
        form = TaskForm()
    else:
        #data given using POST, need to store them
        form = TaskForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit = False)
            new_task.assigned_to = request.user
            new_task.save()
            return HttpResponseRedirect(reverse('team_tasks_managers:tasks'))
    
    context = {'form': form}
    return render(request, 'team_tasks_managers/new_task.html', context)

def cross_off(request, task_id):
    task = Task.objects.get(id = task_id)
    task.completed = True
    task.save()
    tasks = Task.objects.filter(assigned_to=request.user).order_by('description')
    context = {'tasks': tasks}
    return render(request, 'team_tasks_managers/tasks.html', context)

def uncross(request, task_id):
    task = Task.objects.get(id = task_id)
    task.completed = False
    task.save()
    tasks = Task.objects.filter(assigned_to=request.user).order_by('description')
    context = {'tasks': tasks}
    return render(request, 'team_tasks_managers/tasks.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('team_tasks_managers:index'))

def register(request):
    """Registering a new user"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            
            authenticated_user = authenticate(username = new_user.username,
            password = request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('team_tasks_managers:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

team_tasks_managers/templates/team_tasks_managers/base.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

<!doctype html>
<html lang="eng">
<head>
    <meta charset = "utf-8">
    <meta http-equiv="X-UA-Compatibile" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TeamTasks</title>
    <link rel="stylesheet" href = "{% static 'css/style.css' %}">
</head>

<body>

    <!--static navigation bar-->
    <nav class="navbar navbar-defualt navbar-fixed-top" id="navbar_whole">
        <div class = "container">

            <div class = "navbar-header">
                <!--button type="button" class = "navbar-toggle-collapsed"
                    data-toggle ="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                </button-->
                <a class = "navbar-brand"
                    href = "{% url 'team_tasks_managers:index' %}">
                    Team Tasks Manager
                </a>
            </div>

            
            <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav">
                        <li>
                            <a href = "{% url 'team_tasks_managers:tasks' %}">Tasks</a>
                        </li>
                    </ul>
                {% endif %}

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>Hi, {{user.username}}!</a></li>
                        <li><a href = "{% url 'users:logout' %}">Log out</a></li>
                    {% else %}
                        <li><a href = "{% url 'users:register' %}">Sign Up</a></li>
                        <li><a href = "{% url 'users:login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse-->

        </div>
    </nav>

    <div class="container">

        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        
        <div>
            {% block content %}{% endblock content %}
        </div>

    </div> <!-- /container-->

</body>
</html>

team_tasks_managers/templates/team_tasks_managers/index.html
{% extends "team_tasks_managers/base.html" %}

{% block header %}
    <div class = 'jumbotron'>
        <h1>Track team's tasks easier than ever!</h1>
    </div>
{% endblock header %}

{% block content %}
    {% if user.is_authenticated %}
        <h2>Thanks for using Team Tasks Manager!</h2>
    {% else %}
        <h2>
            <a href="{% url 'users:register' %}">Sign Up</a>,
            to start using Team Tasks Manager.
        </h2>
    {% endif %}
    <h3>
        Add and track your own tasks. Assign tasks to your employees.
    </h3>
{% endblock content %} 

team_tasks_managers/templates/team_tasks_managers/new_task.html
{% extends "team_tasks_managers/base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block header %}
    <h2>Add a new task</h2>
{% endblock header %}

{% block content %}

    <form action = "{% url 'team_tasks_managers:new_task' %}" method = 'post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {%buttons %}
            <button name = "submit" class="btn btn-primary">Add task</button>
        {% endbuttons %}
    </form>
    
{% endblock content %}

team_tasks_managers/templates/team_tasks_managers/task.html
{% extends 'team_tasks_managers/base.html' %}

{% block header %}

    </br>
    <h2>{{ task }}</h2>

{% endblock header %}

{% block content %}

    <h3>Deadline: {{task.deadline}}</h3>

    {% if task.completed %}
        <h3>Completed</h3>
    {% else %}
        <h3>Not completed</h3>
    {% endif %}

{% endblock content %}

team_tasks_managers/templates/team_tasks_managers/tasks.html
{% extends "team_tasks_managers/base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block header %}

    </br>
    <h1>Tasks</h1>

{% endblock header %}

{% block content %}

    <table class = "table table-compact table-bordered">
        {% for task in tasks %}
            {% if task.completed %}
                <tr>
                    <td class = "striker"><a href = "{% url 'team_tasks_managers:task' task.id %}">{{ task }}</a></td>
                    <td><center><a href = "{% url 'team_tasks_managers:uncross' task.id %}">Uncross</a></center></td>
                </tr>
            {% else %}
                <tr>
                    <td><a href = "{% url 'team_tasks_managers:task' task.id %}">{{ task }}</a></td>
                    <td><center><a href = "{% url 'team_tasks_managers:cross_off' task.id %}">Cross off</a></center></td>
                </tr>
            {% endif %}
         {% empty %}
            <h2>No tasks to display</h2>
        {% endfor %}
    </table>

    <h3><a href = "{% url 'team_tasks_managers:new_task' %}">Add task</a></h3>

{% endblock content %}

users/templates/users/login.html
{% extends "team_tasks_managers/base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block header %}
    <h2>Log In</h2>
{% endblock header %}

{% block content %}

    {% if form.errors %}
    <p>Incorrect username or password. Please try again.</p>
    {% endif %}

    <form method = "post" action = "{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name = "submit" class="btn btn-primary">Log In</button>
        {% endbuttons %}

        <input type = "hidden" name = "next" value = "{% url 'team_tasks_managers:index' %}" />
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends "team_tasks_managers/base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
    <form method = "post" action = "{%url 'users:register' %}">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name = "submit" class="btn btn-primary">Sign Up</button>
        {% endbuttons %}
        <input type = "hidden" name = "next" value = "{% url 'team_tasks_managers:index' %}"/>
    </form>
{% endblock content %}